version: "3.8"
services:
  app:
    build:
      args:
        user: app
        uid: 1000
      context: ./application
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./application:/var/www
    networks:
      - app

  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_PASSWORD: app
      MYSQL_USER: app
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - app-db:/var/lib/mysql
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./application:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app

  node:
    image: node:15.1.0
    container_name: node
    volumes:
      - ./application:/app
      - app-node_modules:/app/node_modules
    working_dir: /app
    restart: unless-stopped
    ports:
      - 8080:8080
    tty: true
    command: bash -c "npm install && npm run watch"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  app-db:
  app-node_modules:
